### ISSUE TITLE
Add admin and non admin users

### ISSUE THREAD

**Issue by tomekowal** [lambdaacademy/2015.01_elixir#1]
How to authenticate:
http://stackoverflow.com/questions/26055501/how-to-restrict-access-to-certain-routes-in-phoenix
http://api.phoenixframework.org/Phoenix.Controller.html

**Comment by ppikula** [comment]
I didn't participate in the last meeting and this issue is unclear for me. 
Can your provide more details about the requirements: 
- what information should I store (email?, password?, nickname?, local/remote_paritcipant?)
- should I send mail with confirmation token? 
- what is the difference between a normal user and an admin user ? 
- should I implement "I forgot my password" option ? 

In my opinion user story is a good option, for example: 
**As an** admin user **I want to** block user accounts **so that** I can block spammers

**Comment by tomekowal** [comment]
True! Thanks for pointing that out:
**As an** admin user **I want to** manually create user accounts **so that** only users, who bought tickets have their accounts.
**As a** user **I want to** change my password **so that** it is not the same as one send in plain text by admin.
**As an** admin user **I want to** change other users password **in case** they forget their password.

To answer your other questions:
- email, password and account type (regular/admin) is enough; we can add nickname, but in that case, user should be able to use both email or nickname to authenticate
- we don't plan to send any emails, admins will crete accounts and send initial password to users, who can than change it
- normal user/regular user is participant, who can watch live stream and vote for talks; admin can additionally create users and add talks, which users will later grade
- in case someone forgot their password, admin can reset it and send it to the user
